import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Sidebar } from "../components/Sidebar";
import { AppbarClient } from "../components/AppbarClient";

export const metadata: Metadata = {
  title: "Docs",
  description: "Generated by create turbo",
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
  <div>
    <AppbarClient />
      <div className="flex">
    <Sidebar  isCollapsed={false} key={1} />
            {children}
            </div>
    </div>
  );
}
